version: '3.4'

services:
  cherryserver:
    image: cherryserver
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 5000:5000/tcp
      - 5000:5000/udp
    networks:
      - mongoCluster
networks:
  mongoCluster: