version: '3.4'

services:
  cherryserver:
    image: cherryserver
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 5000:5000
